# Generated by Django 4.1.4 on 2022-12-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about_home_article_home_contact_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=202)),
            ],
        ),
    ]
